import { AdpSnapshotSchema, type AdpSnapshot } from './schemas';

// Fetches our own static asset (public/adp-snapshot.json), generated by
// scripts/fetch-adp.mjs and refreshed daily by
// .github/workflows/refresh-adp.yml. This is same-origin, unlike a direct
// call to Fantasy Football Calculator (no CORS support there — see
// domain/adp.ts), so it works from the deployed static site with no backend.
export async function fetchAdpSnapshot(): Promise<AdpSnapshot> {
  return fetchSnapshot('adp-snapshot.json');
}

// The same shape from a different source: public/adp-real-snapshot.json,
// generated by scripts/fetch-mfl-adp.mjs from real (non-mock) redraft leagues
// on MyFantasyLeague, refreshed by the same workflow. Kept as its own file
// rather than extra entries in the FFC snapshot so the two can never be blended
// behind one badge — rankAdpEntries falls a player through to the next entry
// when they're missing from the closest one, which is right within a source and
// wrong across two of them.
export async function fetchRealAdpSnapshot(): Promise<AdpSnapshot> {
  return fetchSnapshot('adp-real-snapshot.json');
}

async function fetchSnapshot(file: string): Promise<AdpSnapshot> {
  // Cache-bust. Vite content-hashes JS/CSS, but files in public/ keep a stable
  // filename forever, so the browser and Pages' CDN will happily serve a
  // months-old copy of this one — confirmed the hard way: a stale cache pinned
  // a player at his late-July ADP long after the committed snapshot had moved
  // on, which reads as "the app's ADP is wrong" rather than "the file is old".
  const url = `${import.meta.env.BASE_URL}${file}?t=${Date.now()}`;
  const res = await fetch(url, { cache: 'no-store' });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return AdpSnapshotSchema.parse(await res.json());
}
