import { AdpSnapshotSchema, type AdpSnapshot } from './schemas';

// Fetches our own static asset (public/adp-snapshot.json), generated by
// scripts/fetch-adp.mjs and refreshed twice weekly by
// .github/workflows/refresh-adp.yml. This is same-origin, unlike a direct
// call to Fantasy Football Calculator (no CORS support there — see
// domain/adp.ts), so it works from the deployed static site with no backend.
export async function fetchAdpSnapshot(): Promise<AdpSnapshot> {
  const url = `${import.meta.env.BASE_URL}adp-snapshot.json`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return AdpSnapshotSchema.parse(await res.json());
}
