import { OutlookSnapshotSchema, type OutlookSnapshot } from './schemas';

// Fetches our own static asset (public/outlook-snapshot.json), generated by
// scripts/fetch-outlooks.mjs and refreshed twice weekly by
// .github/workflows/refresh-adp.yml. Same-origin, so no CORS concern — see
// CLAUDE.md's "Player outlook pipeline" for why this is snapshotted at CI
// time rather than fetched live even though ESPN's endpoint allows it.
export async function fetchOutlookSnapshot(): Promise<OutlookSnapshot> {
  const url = `${import.meta.env.BASE_URL}outlook-snapshot.json`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return OutlookSnapshotSchema.parse(await res.json());
}
