import { OutlookSnapshotSchema, type OutlookSnapshot } from './schemas';

// Fetches our own static asset (public/outlook-snapshot.json), generated by
// scripts/fetch-outlooks.mjs and refreshed daily by
// .github/workflows/refresh-adp.yml. Same-origin, so no CORS concern — see
// CLAUDE.md's "Player outlook pipeline" for why this is snapshotted at CI
// time rather than fetched live even though ESPN's endpoint allows it.
export async function fetchOutlookSnapshot(): Promise<OutlookSnapshot> {
  // Cache-bust for the same reason as the ADP snapshot: public/ filenames are
  // stable, so without this the CDN and browser can pin a long-stale copy.
  const url = `${import.meta.env.BASE_URL}outlook-snapshot.json?t=${Date.now()}`;
  const res = await fetch(url, { cache: 'no-store' });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return OutlookSnapshotSchema.parse(await res.json());
}
