import { z } from 'zod';

// Runtime validation for the Sleeper responses we consume. Schemas are lenient
// on purpose: Sleeper's API is only partly documented (and its ADP/projections
// endpoint is undocumented), so we validate the fields we rely on and tolerate
// anything else. Unknown keys are stripped by default.

export const LeagueSchema = z.object({
  league_id: z.string(),
  name: z.string().optional(),
  season: z.string().optional(),
  draft_id: z.string().nullish(),
  previous_league_id: z.string().nullish(),
  roster_positions: z.array(z.string()).optional(),
  total_rosters: z.number().optional(), // team count; used by the username→league picker list
  // `rec` (points per reception) is what we use to pick the closest ADP
  // snapshot format (0 = standard, 0.5 = half-ppr, 1 = ppr) — see domain/adp.ts.
  scoring_settings: z.record(z.string(), z.number()).nullish(),
  // Only `max_keepers` is read (see domain/leagueSettings.ts); passthrough keeps
  // the rest rather than failing validation on Sleeper's many other settings.
  settings: z.looseObject({ max_keepers: z.number().nullish() }).nullish(),
});
export type SleeperLeague = z.infer<typeof LeagueSchema>;

// GET /v1/user/<user_id>/leagues/nfl/<season> returns the same shape as a
// single league fetch (verified live against the Sleeper API), so this is a
// plain alias rather than a distinct schema.
export const LeaguesForUserSchema = z.array(LeagueSchema);

export const UserSchema = z.object({
  user_id: z.string(),
  display_name: z.string().optional(),
  avatar: z.string().nullish(),
  metadata: z.object({ team_name: z.string().optional() }).nullish(),
});
export type SleeperUser = z.infer<typeof UserSchema>;
export const UsersSchema = z.array(UserSchema);

// GET /v1/user/<username> — the single-user lookup used by the username→league
// picker. Distinct from UserSchema above: that one models a league member (has
// `metadata.team_name`), this models the standalone account lookup response.
export const UserLookupSchema = z.object({
  user_id: z.string(),
  username: z.string().optional(),
  display_name: z.string().optional(),
  avatar: z.string().nullish(),
});
export type SleeperUserLookup = z.infer<typeof UserLookupSchema>;

export const RosterSchema = z.object({
  roster_id: z.number(),
  owner_id: z.string().nullable(), // orphan/unclaimed teams can have a null owner
  players: z.array(z.string()).nullish(),
});
export type SleeperRoster = z.infer<typeof RosterSchema>;
export const RostersSchema = z.array(RosterSchema);

export const DraftSchema = z.object({
  draft_id: z.string().optional(),
  type: z.string().optional(), // only trust pick math when this is 'snake'
  // draft_order: user_id -> slot. Sleeper sets this to null (with a default
  // identity slot_to_roster_id) until the commissioner actually sets the
  // order — see hasKnownDraftOrder in domain/draftOrder.ts.
  draft_order: z.record(z.string(), z.number()).nullish(),
  slot_to_roster_id: z.record(z.string(), z.number()).nullish(), // slot -> roster_id
  settings: z.object({ rounds: z.number().optional() }).nullish(),
});
export type SleeperDraft = z.infer<typeof DraftSchema>;

export const PickSchema = z.object({
  player_id: z.string().nullish(),
  round: z.number(),
  roster_id: z.number(),
  is_keeper: z.boolean().nullish(),
});
export const PicksSchema = z.array(PickSchema);

// GET /v1/draft/<draft_id>/traded_picks — already scoped to that draft's
// season (unlike the league-wide endpoint, which aggregates a league's entire
// multi-season trade history). roster_id = original owner of this round's
// pick, owner_id = current holder; absence from the list means untraded.
export const TradedPickSchema = z
  .object({
    round: z.number(),
    season: z.string(),
    roster_id: z.number(),
    owner_id: z.number(),
    previous_owner_id: z.number().nullish(),
  })
  .transform((p) => ({
    round: p.round,
    season: p.season,
    rosterId: p.roster_id,
    ownerId: p.owner_id,
    previousOwnerId: p.previous_owner_id ?? null,
  }));
export type SleeperTradedPick = z.infer<typeof TradedPickSchema>;
export const TradedPicksSchema = z.array(TradedPickSchema);

// The players dictionary is ~5MB / ~11k entries and is cached ~20h. We keep it
// as a typed shape and slim it defensively rather than running per-entry schema
// validation on every field (a needless per-load cost). See ensurePlayersLoaded.
export interface RawPlayer {
  first_name?: string;
  last_name?: string;
  position?: string | null;
  fantasy_positions?: string[] | null;
  team?: string | null;
  search_rank?: number | null;
  birth_date?: string | null;
  espn_id?: number | string | null;
}
export type PlayersResponse = Record<string, RawPlayer | null>;

// Our own static asset (public/adp-snapshot.json), generated by
// scripts/fetch-adp.mjs from Fantasy Football Calculator's ADP API and
// refreshed by a scheduled CI job (.github/workflows/refresh-adp.yml) — not
// third-party traffic, but still validated since it's parsed as untyped JSON.
export const AdpSnapshotPlayerSchema = z.object({
  name: z.string(),
  position: z.string(),
  team: z.string().nullish(),
  adp: z.number(),
  // Earliest/latest pick this player was actually taken across the real
  // drafts behind this entry — display only (e.g. "high/low"), never fed into
  // the value metric. Nullish: older snapshots and some FFC entries omit them.
  high: z.number().nullish(),
  low: z.number().nullish(),
});
export const AdpSnapshotEntrySchema = z.object({
  // Optional because current snapshots don't carry it: FFC ignores its own
  // `teams` parameter (verified — every format returns identical data for
  // 8/10/12/14), so the generator stopped emitting a dimension that never
  // varied. Kept nullish so a snapshot cached before that change still
  // validates instead of dropping the app to the rank proxy.
  teams: z.number().nullish(),
  format: z.string(),
  meta: z
    .object({
      totalDrafts: z.number().optional(),
      startDate: z.string().nullish(),
      endDate: z.string().nullish(),
    })
    .optional(),
  players: z.array(AdpSnapshotPlayerSchema),
});
export const AdpSnapshotSchema = z.object({
  fetchedAt: z.string(),
  attribution: z.string().optional(),
  entries: z.array(AdpSnapshotEntrySchema),
});
export type AdpSnapshot = z.infer<typeof AdpSnapshotSchema>;
export type AdpSnapshotEntry = z.infer<typeof AdpSnapshotEntrySchema>;

// FantasyCalc player values, our own generated asset (scripts/fetch-fantasycalc.mjs).
// Keyed by Sleeper id — FantasyCalc supplies one on every row, so no name
// matching is needed. `rank` is a *value* ranking, not ADP; see
// src/domain/marketValue.ts for why that distinction matters.
export const ValueSnapshotEntrySchema = z.object({
  numQbs: z.number(),
  // Optional so snapshots taken before the matrix existed still validate. These
  // MUST be declared: zod strips undeclared keys, so omitting them silently
  // discards the league-size/scoring dimensions and every entry collapses to
  // "1 QB" with no way to tell which one was picked.
  numTeams: z.number().optional(),
  ppr: z.number().optional(),
  players: z.array(
    z.object({
      id: z.string(),
      rank: z.number(),
      value: z.number().nullable().optional(),
    }),
  ),
});
export const ValueSnapshotSchema = z.object({
  fetchedAt: z.string(),
  attribution: z.string().optional(),
  entries: z.array(ValueSnapshotEntrySchema),
});
export type ValueSnapshot = z.infer<typeof ValueSnapshotSchema>;

// The league's shared keeper picks, stored as a single JSON file in a GitHub
// Gist so every manager sees the same locked-in selections — see CLAUDE.md's
// "Shared keeper picks". This is the one piece of app data that isn't
// device-local, and it's written by other people's browsers, so it's validated
// on read like any third-party payload. `savedByName` is a display convenience
// only; `savedBy` (the Sleeper user_id) is what ownership is actually checked
// against.
export const SharedKeeperTeamSchema = z.object({
  playerIds: z.array(z.string()),
  savedBy: z.string(),
  savedByName: z.string(),
  savedAt: z.string(),
});
export type SharedKeeperTeam = z.infer<typeof SharedKeeperTeamSchema>;

// leagues -> leagueId -> rosterId -> that team's locked picks. Keyed by league
// so one gist can back more than one league without collisions.
export const SharedKeepersSchema = z.object({
  version: z.literal(1),
  leagues: z.record(z.string(), z.record(z.string(), SharedKeeperTeamSchema)),
});
export type SharedKeepers = z.infer<typeof SharedKeepersSchema>;

// public/outlook-snapshot.json, generated by scripts/fetch-outlooks.mjs from
// ESPN's public (undocumented) fantasy football API and refreshed by the same
// scheduled CI job as ADP — see CLAUDE.md's "Player outlook pipeline".
// espnId is matched against Sleeper's own espn_id field on each player.
export const OutlookSnapshotPlayerSchema = z.object({
  espnId: z.number(),
  name: z.string(),
  outlook: z.string(),
});
export const OutlookSnapshotSchema = z.object({
  fetchedAt: z.string(),
  attribution: z.string().optional(),
  players: z.array(OutlookSnapshotPlayerSchema),
});
export type OutlookSnapshot = z.infer<typeof OutlookSnapshotSchema>;
