import { ValueSnapshotSchema, type ValueSnapshot } from './schemas';

// Fetches our own static asset (public/value-snapshot.json), generated by
// scripts/fetch-fantasycalc.mjs and refreshed daily by
// .github/workflows/refresh-adp.yml. Same-origin, unlike a direct call to
// api.fantasycalc.com (which sends no CORS headers).
export async function fetchValueSnapshot(): Promise<ValueSnapshot> {
  // Cache-bust for the same reason as the ADP snapshot: public/ filenames are
  // stable, so without this the CDN and browser can pin a long-stale copy.
  const url = `${import.meta.env.BASE_URL}value-snapshot.json?t=${Date.now()}`;
  const res = await fetch(url, { cache: 'no-store' });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return ValueSnapshotSchema.parse(await res.json());
}
